[package]
name = "rustytherobot"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0.1" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
directories = { version = "6" }
serde = { version = "1" }
serde_json = { version = "1" }
ron = { version = "0.12" }
anyhow = { version = "1" }
rand = { version =  "0.10" }
